Repository gitcpu-io/install-prow, pull requests merged in 2022-01, with the labels that each got.

#5 Create a.txt
  a.txt
Labels: lgtm, approved, size/XS

#6 Update a.txt
  a.txt
Labels: lgtm, approved, size/XS

#7 Update a.txt
  a.txt
Labels: lgtm, approved, size/XS

#8 Update a.txt
  a.txt
Labels: lgtm, approved, size/XS

#9 Update a.txt
  a.txt
Labels: lgtm, approved, size/XS

#10 Update a.txt
  a.txt
Labels: lgtm, approved, size/XS

#11 Update a.txt
  a.txt
Labels: kind/bug, lgtm, approved, size/XS

#13 Create aaa
  aaa
Labels: lgtm, size/XS, approved

#16 Update aaa
  aaa
Labels: lgtm, size/XS, approved

#17 Update aaa
  aaa
Labels: lgtm, size/XS, approved

#18 Update aaa
  aaa
Labels: lgtm, size/XS, approved

#21 update
  Readme.md
Labels: size/M

#24 配置公有云域名
  starter.yaml
Labels: size/XS
